### ISSUE TITLE
[Tracker] Basic Stats Interface

### ISSUE THREAD

**Issue by mrtryhard** [mrtryhard/mytryhard#17]
## Todo
- [x] Pie Chart Generator 
  - [x] Generate entries repartition pie chart (aka what sport the person does the most)
- [x] Summary Panel 
  - [x] Show Totals 
    - [x] Show total total of time spent in sport since tracking 
    - [x] Show total distance done (for any option)
  - [x] Show Averages
    - [x] Show average time spent for given sport 
    - [x] Show average distance done for given sport 
  - [x] Show semi advanced
    - [x] Show median of time 
    - [x] Show median of distance 
    - [x] Show mode of distance 
  - [x] Show advanced 
    - [x] Time per distance for given sport 
- [x] Not in this version 
  - [x] Histogram Generator
  - [x] Generate global performance histogram
- [x] Removed from todo
  - [x] Allow downloading of charts
  - [x] Generate range based performance histogram
### Explanations

For the pie chart, the most generic, the better. It will be used in admin panel eventually for stats comprehensions.   

For the histogram, a bit of the same thing.

**Comment by mrtryhard** [comment]
Updated the todo list to be clearer. 
Right now need to generalize the Pie Chart generator so I can use it elsewhere.

**Comment by mrtryhard** [comment]
For this milestone, the Pie Chart is most than sufficient.

**Comment by mrtryhard** [comment]
Histogram cancelled for this issue. 
Will be ported to 0.3.6.
